/* XPM */
static char *b211136f67184305d74f0f7bc9b8c1f2KzJvbcUTUU0Jgwch[] = {
/* columns rows colors chars-per-pixel */
"100 100 112 2 ",
"   c #231E1F",
".  c #2B1D1D",
"X  c #3F1719",
"o  c #331B1B",
"O  c #39181A",
"+  c #2C211E",
"@  c #32221F",
"#  c #39211C",
"$  c #231E20",
"%  c #291E20",
"&  c #2E2121",
"*  c #332222",
"=  c #3B2521",
"-  c #431617",
";  c #4C1415",
":  c #431718",
">  c #521314",
",  c #5C1112",
"<  c #650E0F",
"1  c #6C0C0C",
"2  c #750B0C",
"3  c #7E090A",
"4  c #680D11",
"5  c #45251E",
"6  c #48251D",
"7  c #422620",
"8  c #4E2B21",
"9  c #522B22",
"0  c #623224",
"q  c #6A3223",
"w  c #713526",
"e  c #773926",
"r  c #7B3925",
"t  c #8A0607",
"y  c #820708",
"u  c #8A0608",
"i  c #820909",
"p  c #833B25",
"a  c #883C26",
"s  c #983F25",
"d  c #8E4024",
"f  c #974023",
"g  c #9C4225",
"h  c #9F4328",
"j  c #A34326",
"k  c #AC4627",
"l  c #AF4827",
"z  c #AE492C",
"x  c #B24625",
"c  c #B24827",
"v  c #BB4B27",
"b  c #B34828",
"n  c #BA4B2A",
"m  c #C44B27",
"M  c #C74B27",
"N  c #C74D26",
"B  c #C34B28",
"V  c #C34B29",
"C  c #C24C29",
"Z  c #C84F2A",
"A  c #C6502A",
"S  c #C7522B",
"D  c #C8512B",
"F  c #C9512B",
"G  c #CB522B",
"H  c #CD522B",
"J  c #CF522B",
"K  c #DD5327",
"L  c #D0512B",
"P  c #D0522A",
"I  c #D2542A",
"U  c #D4542A",
"Y  c #D4552C",
"T  c #D6572E",
"R  c #D7572E",
"E  c #DB5429",
"W  c #D8552A",
"Q  c #DB542A",
"!  c #DD5428",
"~  c #DD5429",
"^  c #DC5529",
"/  c #DD5529",
"(  c #D9532C",
")  c #E25629",
"_  c #E4572A",
"`  c #E6572A",
"'  c #E2562C",
"]  c #E2582A",
"[  c #E65829",
"{  c #EA5829",
"}  c #E8592B",
"|  c #EA582B",
" . c #EF592B",
".. c #EE5A2A",
"X. c #EE5B2B",
"o. c #EF5B2B",
"O. c #E85A2C",
"+. c #EF592C",
"@. c #ED5A2C",
"#. c #ED5A2D",
"$. c #EC5B2E",
"%. c #EE5C2D",
"&. c #F05929",
"*. c #F05A29",
"=. c #F15A29",
"-. c #F1582B",
";. c #F0592B",
":. c #F2592A",
">. c #F15A2A",
",. c #F15A2B",
"<. c #F2592C",
"1. c #F05A2E",
/* pixels */
"t t t t , > , > @ o o + =.=.=.=.$ $ $ $ { o.>. .0 0 0 0 - - - - u u t t t t t t 1 1 2 1 .   $ . { -.-. .        G Y R R a a a a o o . o i t t t t t t t i i i i + + $ $ =.=.=.=.  $     k c l l c x x x ",
"t t t t , , , , + o + o =.=.=.=.$ $ $ $ o.o.=.*.0 0 0 0 : : - - u u t t t t t t 1 2 1 1     $ $ +.+.+.+.        Y Y R R a a a a o o o . t t t t t t t t i y i t $ $ $ $ #.=.=.<.        l c l l c c x c ",
"u t t t , > , , o @ . + =.=.=.=.+ $ $ $  .*.*. .0 0 0 0 : : X X u u u u t t t t 1 1 1 1 .     $ $.1.| 1.        R R R R a a a a . o o o t t t t t t t t i y y i $ $ $ $ :.:.=.<.        l l l l x x x l ",
"t t u t , , > > + o @ o =.=.=.=.$ $ $ $ { o.*.*.0 0 9 0 : : X O u u u u t t t t 1 2 1 2       $ $.1.1.1.        R R R R a a a a o o . . t t t t t t t t y y y 3 $ $ $ $ :.:.:.:.$       l l l l x x x x ",
"> > > ; $ $ $ $ 6 6 6 7 =.<.=.=.$ $ $ $  . .{ =.e e e e + $ $ $ : : : : 4 , , , $       * * * * 1.1.<.%.& $     T T T T j h h h $ $ $ $ o O o O 4 4 4 4         . $ $ . :.=.<.<.        x k k x B B B B ",
"; > > ; $ $ $ $ 7 8 6 6 =.=.<.<.$ $ $ $  .=. .=.e e e e $ $ $ $ : : : : < , , ,         * * * * <.$.%.1.$ $     T T T T h h h h $ $ $ $ O o = O 4 4 4 4 $   $ $ $ . % $ :.<.<.<.  $   $ c z x k B B B B ",
"> > > >   $ $ $ 6 7 5 6 <.=.<.=.$ $     *.*.=.=.e e e e $ $ $ $ : : : : 4 , , ,     $ $ = * * * 1.<.$.#.$ $ $ $ T T T T h h h h $ $ $   O O O o 4 4 4 4 $   $ $ % . $ % <.<.<.<.    $   z k z k B B B B ",
"> ; ; > $ $ $ $ 6 6 8 5 ,.o.<.<.$ $ $ +  .*.=.=.e e e e $ $ $ $ : : X X , , , ,   $ $ $ * * * * $.<.<.$.$ $ $ $ T T T R h h h h $ $ $   O o O @ 4 4 4 4 $ $ $ $ % $ . % <.<.<.<.        z x z k B B B B ",
"  +     P P L L <.<.>.o.g f g f $ $   $ r p r p +.+.#.<.! ~ / / * @ $ @         n n n n =.-. .+.c c c c         0 0 q q $.1.1.<.{ $.O.O.= = = =     +   j j j j  . . .=.G A G S & $ $ $ 8 8 8 8 %.%.O.#.",
"        P L L L >.<.%.>.g g g f $ $ $ $ p r p r +.+.+.+.~ / / / * * @ @         n n n n #.=. .=.c c c c         q 0 0 q 1.1.#.<.[ [ O.O.= = = =         j j j j  . .=. .G S S S $ $ $ $ 8 8 8 8 $.%.<.#.",
"        P P J L >.>.>.>.h s s g $ $     r p r p +.+.<.O.! ~ ! / . @ % @         n n n n =. .=.{ c c l l $ $     q q 0 q =.<.=.<.[ o.[ { = = = =     $   j j j k  . . . .S S S S $ $ $ $ 8 8 7 8 <.%.%.$.",
".   + + P P J J >.>.>.>.s s j s $ $     p r p r +.+.#.=.~ ! ! W @ * @ @         n n n n =.=. .{ c c l j $       0 q q q <. .<.<.{ { [ { = = = =     $ . j j j j *. .=. .S S S b $ $ $ $ 8 8 9 5 O.%.<.O.",
"0 0 0 0  . . . .% % $ $ $ $ $ $ < < < <           $ $ $ ] ] ' ' a s d d @ # # @ <.<.=.<.+ + + + + $ $ $ , , , <   .     & $ $ $ N N N N x x x x         O.1.<.%.* # = = & $ $ $ - > , > . o o o $ $ $ $ ",
"0 0 0 0  . . . .% $ % $ $ $ $ $ < , , <           $     ] ] ' ' f a d d # # # # =.<.=.<.+ + + + $ $   $ < , , , . .   + $ $ $ $ N N N N x x x x         <.1.$.1.= = = = $ $ $ $ > > > > . o . o * $ $ + ",
"9 0 0 0  . .#.<.$ $ $ $ $ $ $ $ < < < <           $     ] ] ^ ] d d d d # # # # =.<.>.=.+ + + +         , , , , .   $   $ $ $ $ M N M M x x x x         <.$.+.$.= = = = $ $ $ $ > > > > o o o . $ $ $ $ ",
"0 0 0 0 -.+.#.<.% $ $ $ $ $ $ $ < < < <         $   $ $ ] ] ] ^ d d d d # o # # =.=.>.=.+ + + +     $   , < , , . . $ $ $ $ $ $ M M M M x x x x         <.#.+.$.= = = = $ $ $ $ > > , > . o . o $ $ $ $ ",
"0 0 0 0 { { *.*.$       3 3 t t t t t t t t t t       $ A H I I d d d d # # # # *...o. .$ $ $ + 3 t t t t t t t t t t t .     + z z z z x x x x %       1.1.1.1.$ $ $ $ i 3 i 3 t t t t t t i t . o o O ",
"0 0 0 0 *.*.*.*.$ $   $ t y t t t t t t t t t t   $   $ I I I I d d d d # # # # *... .o.$ $ $ $ y t t t t t t t t t t t .   $   z z z z x x x x % %     1.1.1.1.$ $ $ $ 3 i 3 i t t t t t t t t o o O o ",
"0 0 0 9 { { *.[ $ $     t t t t t t t t t t t t $ $ $   I I I I d d d d + # # # *.*.o.o.$ $ $ $ t t t t t t t t t t t t $ $ &   z z z z x x x x     .   | 1.1.1.& $ $ & i 3 i 3 t t t t t t t t o o o o ",
"0 0 0 0 *.*.*.*.        t t t t t t t t t t t t $       I I I I d d d d # # # o *.*.o. .$ $ $   t t t t t t t t t t t t $ $ $ $ z z z z x x x x       . 1.1.#.#.$ $ $ & 3 i 3 i t t t t t t t t o o o o ",
"0 0 0 0 *.o.o.{         t t t u t t t t t t t t     $   P U P U d d d d # @ # # o.o.*.>.$ $ $ $ t t t t t t y t u u u t $ $ $ $ z z z z x x x x         =.+.#.#.$ $ $ & 3 3 2 3 t t t t t t t t o o o O ",
"6 0 0 0  .o.o.o.        t t t t t t t t t t t t         U P U P d d d d # # # # *.>.*.o.$ $ $ $ t t t t y t t t u u u t $ $ $ $ z z z z x x x x         -.+.1.1.$ $ $ $ 3 3 i 3 t t t t t t t t O o o O ",
"0 0 0 0 o.......$   $ $ t u t u t t t t t t t t   $   + U U L U d d d d # # # # >.*.>.o.$   $ $ t t t t t t t t u u i t $ $ $ $ z z b x x x x x   .      .#.1.1.& $ $ $ 3 3 3 3 i t t t t y t t o o O * ",
"0 0 0 0 o.......    $   y t t u t t t t t t t t + $   + U U L L d d d d # # # # o.o.>.*.$ $ $ $ t t y t t t t t u u t i $ $ $ $ z z b x x x x x         <.| 1.1.$ $ $ $ 3 3 3 i t t t t t t t i o O o o ",
"0 0 9 0 %.%.$.%.+     $ . o % . t y y y o O o o         W W W W d d d d O # # # =.=.<.<.& $ $   .   .   3 3 3 3 X X X X $ $ $ $ b b b b x x x x     $ $ 1.$.,.%.$ $ $ $ $ $ $ $ 3 2 2 2 ; ; ; ; $ $ $ $ ",
"0 0 0 0 %.%.o.$.$   $ $ o . . . u y y y o o o o         W W W W d d d d # # # # =.-.=.<.$ $       .   . 3 3 3 3 X X X X $ $     b b b b x x x x       $ ,.,.$.%.$ $ $ $ $ $ $ $ 2 2 2 2 ; ; ; ; $ $ $ $ ",
"0 0 0 0 %.%.%.%.    $ $ . . . . y y y y O o o O         W W W ! d d d d # # # # -.=.-.=.$   $   .       3 3 3 3 X X X X $ $   $ x c x x x x x x $   $ $ $.1.%.,.$ $ $ $ $ $ $ $ 2 2 2 2 ; ; ; ; $ $ $ $ ",
"0 0 0 0 %.%.%.%.      $ o . . . y y y y o o o O         W W W L d d d d # + # # =.-.=.=.$ $       .   + 2 3 3 2 X X X X $ $ $ $ x x v x x x x x     & & %.,.,.>.$ $ $ $ $ $ $ $ 2 2 2 2 ; ; ; ; $ $ $ $ ",
"# # @ = %.>.%.O.[ [ =.#.9 9 9 9   $ $ $ * # 7 8 ' O.$.$.O.<.=. .9 9 9 9 . +     [ [ [ [ -.-.:.:.w w w w       $ @ @ @ # I ] ] ] &.&.&.-.q q q q         ! ! ^ ! <.$.1.1.r p p p $ $ $ $   + +   J J U U ",
"# # = = o.%.{ o. . . . .9 9 0 9 $ $ $ $ 7 7 7 7 O.#.$.$.#.<. .-.9 6 9 9 + +   + [ [ [ [ -.-.:.-.w w w w         # # @ @ ] ] ] ] &.&.&.&.q q q q         R ! ^ R #.1.1.1.p p a p   $ $ $       + ( Y Y L ",
"= = @ = { %.%.o. . .=.=.9 9 9 9 $ $ $   7 7 7 7 $.$.$.$.#.+. . .9 9 9 9   + +   { [ _ _ -.-.=.+.w w w w         @ @ @ @ ] ] ] ] *.*.=. .q q q q         ! / / / $.<.<.#.p a a p $ $     +       L Y L ( ",
"# = = = O.%.o.o.=. . . .9 0 9 9 $   $ $ 7 7 7 7 $.$.$.$.=.+. . .9 9 9 6 + .   + _ _ {  .-.-.=.=.w w w w       + # @ @ + ] ] ] ] *.*. .=.q q 0 0         ( ! ( ! %.<.O.<.a a p a $       +   & & Y Y ( L ",
"7 = 7 7 $ $ +   p r r p o.o. .*.%.%.%.#.&.&.&.*.s s h s $ $ $ $ + * o & 9 5 9 9 $ $ $ $ 0 0 0 q  .*.*.*.%.o.%.o.%. .<.#.b l c l             +   q q q q $ $ $ $ 7 8 9 9 $.<.$.$.o.o.o.%.%.%.%.%.Z Z G A ",
"7 7 7 = $ $     r p p p o... . .%.%.%.=.&.&.&.*.s s s s $ $ $ $ * & * % 9 9 9 9 $ $   $ q 0 0 q  .*.&.*. .%. .%.$. .$.=.c l c l               + q q q q $ $ $ $ 8 8 9 9 %.%.<.#.%.{ o.{ %.%.%.%.Z Z Z G ",
"7 = 7 7 $ $     p p p r o.o.=.=.%.%.O.#.&.&. . .s s f s $ $ $ $ * @ % @ 9 8 9 9 $ $ $ & 0 q q q &.&.&.&.%. .$.%.=.%.=.#.k x k c       $         q w w q $ $ $ & 8 9 8 9 <.<.=.#.o.o.%.%.%.%.>.,.Z Z A N ",
"7 5 = # $ $     p r r p o.%.{ { %.%. . .&.&.<.=.s s a a $ $ $ $ % * * @ 9 8 8 9 & $ $ * 0 q q q &.&.&.&.#.$.$.<.O.<.$.<.x x k x       $     .   q q w q $ $ $ & 9 8 9 8 <.#.<.=.o.o.o.O.%.%.%.%.Z Z A C ",
",.=.o.=.G J G J &               k j k k         $ $ $ $ b n n n =.o. .=.=. .o.>.! ! ! ^ + & & +     $   s s s s % * & % $ $ $ $ g j g j 1.1.1.1.=.=.o.o.o.[ [ $.= # # # & $     p d r d = = = =       $ ",
">.%.=.%.J G J G $ $             j k k j $ $     $ $ $ $ n n b n  .=.=.o.=.=.o.o.] ^ ^ ^ & + + @     $ $ s s g f % % % . $ $ $ $ g g j j <.1.1.1.o. .o.*.[ [ [ %.= = # + & $     p d d r = = = =     $ $ ",
" .<.>.=.J J J L       .         k j j k $ $ $ $ $ $ $ $ n n n b  .>.=.=.o.o.o.o.^ ^ ^ ! + + + +         s f f f @ % % *   $     f j f h <.<.1.1.o.o.o.o.o.[ { O.= = # #         d r p d = = # =     $   ",
"=.=.=.%.G J J N     .         . j k k j $ $ $ $ & $ $ $ n b n n >.o.*.o. .o.o.o.^ ^ ^ ! + & + +         s s f f % % % %         j h j h =.<.$.<.o. .o.o.] [ O.[ @ * # @         p d p d = = # #   $     ",
"    &   G J J J ...... .f f s s $ $ $ % p p p p -.-.-.-.( ( ( ~ + & & &         b n n n %.%.=. .x c c c   $ $   q q q 0 %.#.<.1.[ O.{ | = = = =       $ h j h j =.o.o.o.S S S S & $ $ $ 8 8 8 8 _  .$.#.",
"    .   J G J Y .... .o.f f s s $ $ $ $ p p p r -.-.-.-.( ( ~ ( & & & &   &   $ v v n v =.%. .%.x c c c         q q q 0 %.<.1.1.#.[ | | = = = =   $   $ j j j j  .o.o.o.S S S S $ $ $ $ 8 8 8 8 %.{ $.%.",
".       J J J J *. .>.>.s s s s $ $ $ $ p r p p <.+.1.$.( ( ~ ~ & & & & +       n n v n =.o.%.=.c c l c $ $ $   q q q q 1.1.1.1.{ #.{ [ = = = = $   $ $ j j h j  .o. .o.S S G Z $ $ $ $ 8 8 8 8 %.$.$.%.",
"+       J J J J o.o.{ >.s s s s $ $ $ $ p p p p <.<.1.<.( ~ ( ~ & & & &         v n v n %.%.=.o.x c l k $ $     q 0 0 q 1.1.1.1.#.{ { ] = = = = $   $ + h j h g o. .o. .S Z S J $ $ $ $ 8 8 8 8 %.%.$.=.",
"; > ; > $ $ $ $ 6 ; 6 6 =.=.=.o.$ $ $ $ O.<.#.#.e e e e $ $ $ $ : X : : , , , , & $ $ $ + @ @ @ %.<.%.,.$       R R R R h h h h $ $ $ $ O O O O , < < < $ $ $ $ % $ % % =.=.<.-.$ $     k b l l m m m m ",
"> ; > ; $ $ $ $ 6 6 6 6 =.=.=.o.$ $ $ $ <.#.-.#.e e e e $ $ $ $ : : : : , , , , $ $ $ $ * @ @ * =.%.,.%.  $   $ R R R R h h h h $ $ $ + O O O O < < < < $ $ $ $ % % % $ <.<.+.=.$ $ $   l l l l m m m m ",
"; > ; ; $ $ $ $ 6 6 6 6 =.=. .{ $ $ $ $  . . . .e e e r $ $ $ $ : : : : , , , , $ $ $ $ * @ @ @ %.,.%.,.  $ $ $ R R R R h h h h $       O O O O < 1 < < $ $ $ $ % % % %  .#.=.-.$ $     l l l l m m m m ",
"> ; ; X $ $ $ $ 6 6 6 5 >.<.o. .+ $   +  .{  . .e e e w $ $ $ $ 5 : : : , , , , $ $ $ $ @ @ @ @ $.%.,.%.$ $ $ + R R R Y h j g h $       O O O O < < < 1 $ $ $ $ % $ % %  .=.+.+.$       l l l l m m B N ",
"u t t t , , , , * & + o  .*.*.*.$ $ $ $ =.#.*.=.0 0 0 0 : : : : t t t t t t t t 1 2 1 2     . $ %.<.%.$.  $     A S R R d a a a o . o . y u u u u u u u i y 3 y $ $ $ $ :.:.:.:.        l l l l c c x x ",
"u u t u , , , , & & o @ =. .*.*.+ $ $ $  . . .*.0 0 0 0 : : : : t t t t t t t t 1 1 1 1       $ 1.%.%.1.$ $     T T T T a a a a o o o o u u u u u u u u i y y i $ $ $ $ :.:.:.:.    $   l l l l c x x x ",
"t t t t , , > , + . o o =.=.*.*.$ $ $ $  ...*. .0 0 0 0 : : ; : t t t t t t t t 1 2 1 1     $ $ ,.%.,.%.$ $ $   T T T T a a a a . o o o u u u u t t u u i i i i $ $ & $ :.:.:.:.        l l l l x x c x ",
"t t t t > , , > o @ @ . =.=.=.*.$ $ $ $ o. .=.*.0 0 9 0 : : : : t t t t t t t t 1 1 2 4 .   $ $ %.1.%.1.$ $     T T T T a a a a o o o o u u u u t t u u i i i i $ $ $ $ :.:.:.:.  $ $ $ l l l l x c x x ",
"u t t t > , , , o o o + =.=.<.=.$ $ $ $ *.=.*.*.0 0 0 0 * * : : t t t t t t t t 1 2 1 1 $ $ $ $ 1.%.%.,.& &     R R R R a a a a o o o . u t t u t t t t t u i i $ $ $ $ :.:.:.:.    $   l l l l x c x c ",
"t t t t , , , > o + + o <.=.<.=.$ $ $ $  .*. .*.0 0 0 0 X 5 : : t t t t t t t t 1 1 1 1 $ $ $   %.1.1.%.$ $ $   R R R R a a a a . o o o t t t y t t t t y y i i $ $ $ $ :.:.:.:.        l l l l x x x x ",
"t t t t > , , , + o o * =.%.=.=.$ $     *.-.*.*.0 0 0 0 X : : : t t t t t t t t 1 1 1 1 $ $ $ & ,.1.%.1.$ $ $ $ R R R T a a a a o o o o t t u u t t t t i i i i $ + $ $ :.:.=.=.        l l l l x x x x ",
"u t t y , , , , o + + # =.=.=.<.$ +      .*.*.*.0 0 0 9 X : : : t t t t t t t t 1 1 1 2 $ $ $ & %.$.,.%.$ $ $ $ R R R I a a a a o . o o y t u u t t t t i i i i $ $ $ $ -.=.<.=.      $ l l l l c x x l ",
"> > ; >   $ $ $ 5 6 5 6 =. .*.*.$ $ $ $ #. .*...r r r r   $   $ > ; - - < , , , $ $ $ $ + & * * %.$.o.o.$ $ $ $ R R R R j f g j $ . $ $ O O O O 1 4 < < $ $ $ $ + $ +   {  .o.o.      $ x b l l B B B B ",
"> > > >       $ 6 6 6 6 =.=.*.*.$ $ $ $ o.o.....r w r w $ $     - - - - , , , < $ $ $ $ * & * * %.O.o.o.$ $ $ $ R R R R h h g h $ $ $ $ O O O O < 1 < < $ $ $ $ $ + +    . .o. .  $     l l l l B B B B ",
"> ; ; >   $     6 6 6 5 :.*.*.*.$ $ $ $  .o.*...r w r r $ $   $ - - - - , , , , $ $ $ + * * * * %.%.[ o.$ $ $ $ R R R R j g j g $ $ $   O O O O 1 4 < 4 $ $ $ $ + +   +  .o. .o.        l l l l B B B B ",
"> > ; ; $       6 6 5 6 *.:.*.:.  $ $ $ o... ...w p r w $ $ $ + - - - - , , , , $ $ $ + * * * * %.%.^ H $ $ $ $ R R R R h g h j $ $   $ O O O O < 1 < 4 $ $ $ & +   +   o. .o. .        l l l l V B B B ",
"$ & $ $ P P P L *. .*.*.f f f f   $   $ p p p r =.+.+.+.K K K K + & + &   $ $ $ v v v v *.*.o.*.v c c c $ $ $ $ 0 q q 0 >.>.>.>.{ { { { = = = = $ $ $ $ j h j h %.<.<.#.A A G G $ % $ $ 8 9 8 8 #.+.<.#.",
"$ . $ $ P P L L  .*. .*.f f f f     $ $ p p p p +.+.#.+.K ! K K * + @ +     $ $ v v v v *.*...*.c c c c $ $ $ $ q q q q >.>.*.>.{ { { { = 5 = = $ $ $ $ h j h z $.#.$.=.G G G A $ $ $ $ 8 6 8 8 <.$.<.<.",
"  . % $ P P J J *. .*.*.f f f f       + r p p p O. .<.#.! ! ! ! + + & + $ & $ $ v v v v *.*.*.*.c c c c $ $   & q 0 q q =.=.*.*.{ { { #.7 = = = $ $ $ $ j j j j <.%.<.#.G G G A % $ $ $ 8 6 8 8 =.#.#.<.",
".     . J J J J  .*.*.*.f f f f         p p p p <.<.#.#.! ! ! ! + @ + + $ $   $ v v v v *.*...o.c c c c $ $ $ @ q 0 q q =.=.*.*.{ { { #.= = = = $ $ $ $ j j j j %.1.$.O.G A G G $ $ $ $ 9 9 8 8 <.<.-.#.",
"0 0 0 0  . .#.O.                < < < <         .       K ) ) ) d d d d # O # # >.*.*.*.+ &   + $ $ $ $ , , , ,   . .           v N M M x x x x $ . $ $  .-.1.<.= = = = $ $ $ $ > > > > o % o %     $   ",
"q 9 0 0  . . .<.                < < < <   .             ) ) ) ) d d d d # # # # >.*.*.*.& & & & $ $ $ $ , , , < . .   .         N N M M x x x x   $     -.-.$.1.= * * = $ $ $ $ > > , > . o o o         ",
"0 0 0 q $. .$. .                < < < <                 ) ) ) ) d d d d + # # # *.*.*.*.+ & + & $ $ $ $ < < , , .     +         N m m M x x x x   .     #.#.1.1.= = = = $ $ $ $ > > , > % o % o     $ $ ",
"0 0 0 9  . .$. .                < < < <   .             ) ) ) ) d d d d # # # # *.*.*.*.& & & + & $ $ $ , , , <       +         m m M M x x x x   $     { | 1.1.= = * = $ $ $ $ , > > , o o % o     $ $ ",
"0 0 0 0  .o.o. .  $   $ t t t t y t t t t t t t $ $ $ + P P U P d d d d # # # # *.*.o.*.+ + $ $ t t t t u u t t t t t t $ $ $ $ z z z z x x x x         %.$.%.<.$ $ $ $ i i 3 3 t t t t u t t t o o o o ",
"0 0 0 0 o.{ { o.        t t t t t t t t y t t y $ $ $ $ P P P U d d d d # # # + *.*. .*.$   $ $ t t t t u u t t t t t t $ $ $ $ z z z l x x x x   $   $ <.%.<.1.$ $ % $ 3 3 3 3 t t t t u u t t o o O o ",
"0 0 0 0 %.{ %. .      + t t t t t t t t t y t t $ $ $ $ P P U U d d d d # # # # *. .*. .$ $ $ $ t t t t t t t t y t u 3 $ $ $ $ z z x x x x x x     $ & %.$.<.#.$ $ % $ 3 3 3 3 t t t t t t t t O o o O ",
"9 0 0 0  .o. .o.      + t t t t t t t t t t t t $ $ $ + U U U U d d d d # # # # *.*. .*.+ $ $ $ t t t t t t t t t u u 2 $ $ $ $ z z x x x x x x   $ $ & %.1.1.O.$ $ $ $ i 3 3 i t t t t t t t t o o o o ",
"0 0 0 0 o.o.o.%.+ $ $ $ t t t t t t t t u t t t $ $ $ $ c H P I d d d d # # # # =.=.=.=.$ $     t t t t t t t t t u u u $ $ $ $ z z z z x x x x o       $.$.+.<.$ $ $ $ 3 3 3 3 t t t t t t t t O o o o ",
"0 0 9 0 o.%.o.{ $ $ $ $ t t t t t t t t t t t t $ $ $   S S I I d d d d # # O + =.#.=.#.$ $     t t t t t t t t t t u u $ $ $ $ z z z z x x x x .     . $.1.<.#.$ $ $ $ 3 i 3 3 t t t t t t t t o o O o ",
"0 0 0 0 { o.o.%.$ $ $ $ t y t t t t t t t t t t $ $ $ $ I I I I d d d d # # # # =.#.{ =.        t t u u t t t t t u u u $ $ $ $ z z z z x x x x   .     1.1.1.1.$ $ $ $ 3 i 3 i t t t t t t t t o O o o ",
"0 0 0 0 o.o.o.{ $ $ $ $ t t t t t t t t t y t t $ $ $ $ I I I I d d d d # # # # #.=.{ )   $     t u u u t t t t t t t u $ $ $ $ z z z z x x x x         1.1.1.1.% $ $ & 3 3 3 i t t t t t t t t o o o @ ",
"0 0 0 0  .=.%.o.$ $ $ $     o . y y y y o O o O $ $ $ $ I W W W d d d d # # # # =.=.=.<.        + +     3 3 3 3 X X X -     & $ x x z c c x x x         <.=.| 1.$ $ $ $ $       1 2 2 2 > ; ; ; $ $ $ $ ",
"0 0 9 0 {  .o.%.$ $ $ $     + . y y y y o o o o $ $ $ $ W W W W d d d d # # # # =.=.=.=.        .   +   3 3 3 3 X X - X         x b x c x x x x         +.+.1.1.$ $ $ $     . $ 2 2 2 2 ; ; ; ; $ $ $ $ ",
"0 0 0 0 { o.o.o.$ $ $ $ + . . . i y y i o O o . $ $ $ + T ^ W W d d d d * o # # >.>.<.=.              . 3 3 3 3 - X - X         b b b b x x x x          .+.#.#.$ $ $ $       $ 2 2 2 2 ; ; ; - $ $ $   ",
"0 0 0 0 o.o.{ o.$ $ $ $   . . . i i y i O O o + $ $ + + T ^ W W d d d f # @ # # >.>.<.=.        . +     3 3 3 3 X - X -         x b x b x x x x     .   +.<.#.#.$ $ $ $   $   $ 2 2 1 2 ; ; ; ; $ $ $ + ",
"= = # = %.#.O. . .o.%.=.0 9 9 9 + + $ $ 5 7 5 5 %.%.%.#. .=. .*.9 9 9 8 & & + $ ^ $.O.O.*.*.:.:.w w w w $ $ $ $ @ @ @ @ ) ) ) ) <.$.#.+.q q q q         K ( ( K #.1.1.O.p p p p .           . . U U U U ",
"= = 7 # O.%.#.#.o.o.o.=.9 9 9 0 $ $ $ $ 5 5 # 7 o.%.{ %.o. .*.*.9 9 9 8 & & + + ^ ] [ ] *.*.*.*.w w w w $ $ $ $ # # @ @ ) ) ) ) #.<.<.=.q q q q   $     ( K K ( <.$.<.<.p p a p             % + U U U U ",
"= : # = %.$.#. . .o.=.=.9 9 9 9 $ $ $ $ # 7 5 5 $.o.o.%.*.*.*.*.9 9 9 8 $ & $ $ [ [ [ [ *.*.>.>.w w w w $ $ $ $ @ @ @ @ ) ) ) ) $.<.#.<.q q q q         K ( ) K =.:.+.+.a p p p         % % % % U U U U ",
"= = = = #.$.O.{ o. .=.=.9 9 9 9 $ $ $ $ 5 5 5 @ $.o.{ %.*.*.*.*.9 9 8 8 & $ + $ [ [ [ ] *.*.>.[ w 0 w w $ $ + & @ @ @ @ ) ) ) ) $.#.-.-.q q q q   $     ( K ( ( =.-.+.#.p p a a         % % $ % U U U L ",
"7 7 = 7 $ $ $ $ a p p p  .o.{ o. .O.1.$.$.#.o.o.f s f s   $ $   & & * & 9 9 9 9 + + $ $ 8 0 q q $.%.%.%.o.o.{ %.%.o.o.{ x x l x & $ $ $ % % % % q q q q $ $ $   9 8 9 9 -.=.*.*. .%.%. . .=.+.-.A A A A ",
"= 7 7 = $ $ $ $ p r p r  . .%. .%.O.$.1.%.,.o.%.s s s s +       * & * * 9 9 9 9 $ $ $ $ 0 0 q q %.%.o.%.o.o.{ %.%.o.o.%.l c x l & $ $ $ % % % % q q q w . $ $   9 9 9 6 -. .*.&.%.%.=. . . . . .A A A A ",
"= 7 7 = $ $ $   p r p p { %.{ { %.<.1.$.o.o.o.{ s s f s $ $ $ $ * & * = 9 9 9 9 $ $ $ $ q q q q o.%.%.o.o.o.%.{ o.o.o.o.l c b z     $ $ % % % $ w 0 w q $ $ % $ 9 9 9 9 *.*.&.&.=.%. . .&.-.-.-.A A A A ",
"5 7 # 5 $ $ $ + p r d r  . . .) %.O.1.1.o.o.o.o.s f f p $ $ $ $ & * * # 9 9 9 9 $ $ $ $ q q q q %.o.%.O.o.o.o.o.o.%.{ o.c b z z       $ % % % % 0 w w 0 $ $ $ $ 9 6 9 9 &.-.&.&.=.%. . . .&. .*.A A A n ",
"$.<. .o.J G J J                 k j j j         $       x n n n o.o.o.o.*.o.=.=.[ W ) K + o + + + $     f s f f & & + + & $ $ $ j g j j =.-. .*.<.-.<.#.| | _ _ = 7 = =         a p p p * = = =       $ ",
" . .o. .G J J G                 j j k k     .           b n n n %.>.o.o...o.=.=.K K K ) + @ + + $ $     s s f f * & & * $ $ $ $ g j s j =.=.*.*.=.#.#.+.#.| #.' = = 7 =         p p d p = = = =   $   $ ",
" . . .o.R J G J     & +         j k k j     $ .         n n n n %.o.$.$.*.*.*.=.W ! ! K + + + @       $ f g g f & & & & $ $ $ $ g j j s  . .&.*.#. .$.$._ ' #.#.7 = = =         a a a a = * * = $ $ $ $ ",
" . . . .S G J G   $ $ +         k j j j .   $ .         n b n n { o.O.$.>.*.=.=.! ] ! ! + . + +         g f g g & & & & $ $ $ $ j j j j  .-.*.*.<.#.O.] #.O.O.{ 7 = # #       + a p a a = = = = $ $ $ & ",
"$ $ $ $ G G R J =.=.<.>.f g g f $ $ $ $ r p p p 1.+.+.1.( W ! ! + & + + $ $ $ $ v v n C >.%.,.%.c c l l &       q 0 q q %.%.%.%.[ { { [ # = = = $ $ $ $ j j j j =.o.o.o.S S S S $ $ $ & 8 8 8 8 =.<.$.$.",
"  $ $ $ R J Y G =.o.>.>.g f f g $ $ $ % p p p r 1.1.<.1.( ' ! ! + & $ + $ $ $ $ v v v v %.o.%.,.l l c b     $   q 0 q q %.%.%.%.{ [  .#.# = 7 = $ $ $ $ g j j j  .o.{ o.S S S G $ $ $ $ 8 8 8 8 %.#.<.$.",
"    & $ Y G J G =.<.<.<.f f f f $ $ $ $ r p r p +.<.1.+./ / ! ! & + + + $ $ &   n n v v %.%.%.%.c c l l $   $ $ q 0 q q =.%.%.%.O.{ { { = = = = $ $ $ & j j j g %.{ %.o.S S S S $ $ $ $ 8 8 8 8 %.%. .$.",
"    & & J Y J Y =.=.<.%.f j f f $ $ $ $ p p p p <.1.<.+.~ / / / + + & & $ $ & & n C v n %.%.%.o.c l l j         0 q q q %.=.%.%.O.[ $.%.= 7 = = $ $ $ + j j j j o.o.o.o.S S S S $ $ $ $ 8 8 8 8 <.%.=.$.",
"; > > >         # 6 6 6 { *.*.*.$ $ $ $ { %.{ *.e e e e $ $ $ $ @ - - - , < , , +       + @ # @ $.<.,.$.* $ $   G R R R j g g g &   $ $ O O O O 1 1 1 1 $ $ $ % +     + =.=.-.=.        l l l l C C C C ",
"> > > ;         6 6 6 6 *.*.*.*.$ $ $ $ [ o.*.*.e e e e $ $ $ $ - - - - , , , ,         # @ * * $.<.$.,.$ $ $ $ Y Y R R j g j g     $ $ O O O O < < < < $ $ $   .   .   =.=.=.-.        l l l l C C C C ",
"; > > ;         6 6 6 6 :.*.*.*.$ $   +  . .{ { e e e e $ $   + - - - - , , , ,       + * * * * <.$.<.#.$ $ $ $ R R R R f h h f     $ $ O O O o 1 1 < < $ $ * $   . $ +  .=.-.=.        l l l x C C C C ",
"> > ; >         6 6 6 6 >.*.*.*.$ +   + { =.*.*.e e e e $     + - - - - , , , ,       + # * * * <.1.#.=.$ $ $   R R T T h h j h       $ O O O . < < 1 < $ $ $ $       $ =.-.=.-.        l l l k C C C C "
};
